src/Entity/BlogPosts.php
<?php

namespace App\Entity;

use App\Repository\BlogPostsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=BlogPostsRepository::class)
 * @Vich\Uploadable
 */
class BlogPosts
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\ManyToMany(targetEntity=Tags::class, inversedBy="blogPosts")
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="blogPosts")
     */
    private $Author;

    /**
     * @ORM\ManyToMany(targetEntity=Categories::class, inversedBy="blogPosts")
     */
    private $Categories;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"title"})
     */
    private $Slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreateAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $UpdateAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Published;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $FeatureImage;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="blogPosts")
     */
    private $Comments;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="blogPosts", fileNameProperty="FeatureImage")
     *
     * @var File|null
     */
    private $imageFile;

   
    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->Categories = new ArrayCollection();
        $this->Comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return Collection|Tags[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tags $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tags $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    public function getAuthor(): ?Users
    {
        return $this->Author;
    }

    public function setAuthor(?Users $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    /**
     * @return Collection|Categories[]
     */
    public function getCategories(): Collection
    {
        return $this->Categories;
    }

    public function addCategory(Categories $category): self
    {
        if (!$this->Categories->contains($category)) {
            $this->Categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Categories $category): self
    {
        if ($this->Categories->contains($category)) {
            $this->Categories->removeElement($category);
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->Slug;
    }

    public function setSlug(string $Slug): self
    {
        $this->Slug = $Slug;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->CreateAt;
    }

    public function setCreateAt(\DateTimeInterface $CreateAt): self
    {
        $this->CreateAt = $CreateAt;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->UpdateAt;
    }

    public function setUpdateAt(\DateTimeInterface $UpdateAt): self
    {
        $this->UpdateAt = $UpdateAt;

        return $this;
    }

    public function getPublished(): ?bool
    {
        return $this->Published;
    }

    public function setPublished(bool $Published): self
    {
        $this->Published = $Published;

        return $this;
    }

    public function getFeatureImage(): ?string
    {
        return $this->FeatureImage;
    }

    public function setFeatureImage(string $FeatureImage): self
    {
        $this->FeatureImage = $FeatureImage;

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->Comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->Comments->contains($comment)) {
            $this->Comments[] = $comment;
            $comment->setBlogPosts($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->Comments->contains($comment)) {
            $this->Comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getBlogPosts() === $this) {
                $comment->setBlogPosts(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->title;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->UpdatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }
}

src/Entity/Tags.php
<?php

namespace App\Entity;

use App\Repository\TagsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=TagsRepository::class)
 */
class Tags
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"title"})
     */
    private $Slug;

    /**
     * @ORM\ManyToMany(targetEntity=BlogPosts::class, mappedBy="tags")
     */
    private $blogPosts;

    public function __construct()
    {
        $this->blogPosts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->Slug;
    }

    public function setSlug(string $Slug): self
    {
        $this->Slug = $Slug;

        return $this;
    }

    /**
     * @return Collection|BlogPosts[]
     */
    public function getBlogPosts(): Collection
    {
        return $this->blogPosts;
    }

    public function addBlogPost(BlogPosts $blogPost): self
    {
        if (!$this->blogPosts->contains($blogPost)) {
            $this->blogPosts[] = $blogPost;
            $blogPost->addTag($this);
        }

        return $this;
    }

    public function removeBlogPost(BlogPosts $blogPost): self
    {
        if ($this->blogPosts->contains($blogPost)) {
            $this->blogPosts->removeElement($blogPost);
            $blogPost->removeTag($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->title;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 * @Vich\Uploadable
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class Users implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $bio;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"firstname", "lastname"})
     */
    private $slug;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreateAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $UpdateAt;

    /**
     * @ORM\OneToMany(targetEntity=BlogPosts::class, mappedBy="Author")
     */
    private $blogPosts;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="avatar", fileNameProperty="avatar")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function __construct()
    {
        $this->SocialNetworks = new ArrayCollection();
        $this->blogPosts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): self
    {
        $this->bio = $bio;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(?int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->CreateAt;
    }

    public function setCreateAt(\DateTimeInterface $CreateAt): self
    {
        $this->CreateAt = $CreateAt;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->UpdateAt;
    }

    public function setUpdateAt(\DateTimeInterface $UpdateAt): self
    {
        $this->UpdateAt = $UpdateAt;

        return $this;
    }

    /**
     * @return Collection|BlogPosts[]
     */
    public function getBlogPosts(): Collection
    {
        return $this->blogPosts;
    }

    public function addBlogPost(BlogPosts $blogPost): self
    {
        if (!$this->blogPosts->contains($blogPost)) {
            $this->blogPosts[] = $blogPost;
            $blogPost->setAuthor($this);
        }

        return $this;
    }

    public function removeBlogPost(BlogPosts $blogPost): self
    {
        if ($this->blogPosts->contains($blogPost)) {
            $this->blogPosts->removeElement($blogPost);
            // set the owning side to null (unless already changed)
            if ($blogPost->getAuthor() === $this) {
                $blogPost->setAuthor(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->UpdateAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

templates/blog_posts_show/aboutAuthor.html.twig
<div class="about-author d-flex p-4 bg-light">
	<div class="bio mr-5">
		<img src="{{ vich_uploader_asset(singlePost.Author) }}" alt="Image placeholder" class="img-fluid mb-4">
	</div>
	<div class="desc">
		<h3>{{ singlePost.Author.firstname }} {{ singlePost.Author.lastname }}</h3>
		<p>{{ singlePost.Author.bio }}</p>
	</div>
</div>

templates/blog_posts_show/comment.html.twig
<div class="pt-5 mt-5">
	<h3 class="mb-5">
		{% if singlePost.comments|length == 0 %}
			Pas de commentaires
		{% endif %}
		{% if singlePost.comments|length == 1 %}
			{{singlePost.comments|length }} Commentaire
		{% endif %}
		{% if singlePost.comments|length > 1 %}
			{{singlePost.comments|length }} Commentaires
		{% endif %}
	</h3>
	<ul class="comment-list">
		{% for comment in singlePost.comments %}
			<li class="comment">
				<div class="vcard bio">
					<img src="{{ asset(gravatar(comment.email)) }}" alt="Image placeholder">
				</div>
				<div class="comment-body">
					<h3>{{ comment.Author }}</h3>
					<div class="meta mb-3">[{{ comment.updateAt|date("m/d/Y à H:m:s", "Europe/Paris")}}]</div>
					<p>
						{{ comment.content}}
					</p>
				</div>
			</li>
		{% endfor %}

	</ul>

	<!-- END comment-list -->

	<div class="comment-form-wrap pt-5">
		<h3 class="mb-5">Laisser un commentaire</h3>
		<div class="p-5 bg-light">
			{{ form_start(form) }}
				<div class="form-group">
					<label for="name">Votre nom *</label>
					{{form_widget(form.Author)}}
				</div>
				<div class="form-group">
					<label for="email">Email *</label>
					{{form_widget(form.email)}}
				</div>
				<div class="form-group">
					<label for="message">Message</label>
					{{form_widget(form.content)}}
				</div>
				<div class="form-group">
					{{form_widget(form.save)}}
				</div>
			{{ form_end(form)}}
		</div>
	</div>
</div>

templates/blog_posts_show/content.html.twig
<p class="mb-5">
	<img src="{{ vich_uploader_asset(singlePost) }}" alt="" class="img-fluid">
</p>

{{ singlePost.content|raw }}

templates/blog_posts_show/hero.html.twig
<section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url({{ vich_uploader_asset(singlePost) }});" data-stellar-background-ratio="0.5">
	<div class="overlay"></div>
	<div class="container">
		<div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
			<div class="col-md-9 ftco-animate pb-5 text-center">
				<h2 class="mb-3 bread">{{ singlePost.title }}</h2>
				<p class="breadcrumbs">
					<span class="mr-2">
						<a href="{{ path('blog_posts_index') }}">Home
							<i class="ion-ios-arrow-forward"></i>
						</a>
					</span>
					<span class="mr-2">
						<a href="{{ path('blog_posts_blog') }}">Blog
							<i class="ion-ios-arrow-forward"></i>
						</a>
					</span>
					<span>
						{{ singlePost.title }}
					</span>
				</p>
			</div>
		</div>
	</div>
</section>

templates/blog_posts_show/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ singlePost.title }} - YoanDev{% endblock %}

{% block hero %}{% include 'blog_posts_show/hero.html.twig' %}{% endblock %}

{% block body %}
	<section class="ftco-section ftco-degree-bg">
		<div class="container">
			{% for message in app.flashes('success') %}
				<div class="alert alert-success">
					{{ message }}
				</div>
			{% endfor %}
			<div class="row">
				<div class="col-lg-8 ftco-animate">
					{% include 'blog_posts_show/content.html.twig' %}
                    {% include 'blog_posts_show/tag.html.twig' %}
					{% include 'blog_posts_show/aboutAuthor.html.twig' %}
					{% include 'blog_posts_show/comment.html.twig' %}
				</div>
                {% include 'blog_posts_show/sidebar.html.twig' %}
			</div>
		</div>
	</section>
{% endblock %}

{% block javascripts %}
    <script>
    hljs.initHighlightingOnLoad();
    </script>
{%  endblock %}

templates/blog_posts_show/sidebar.html.twig
<!-- .col-md-8 -->
<div class="col-lg-4 sidebar pl-lg-5 ftco-animate">
	<div class="sidebar-box">
		<form action="{{ path('blog_posts_search') }}" class="search-form" method="post">
			<div class="form-group">
			{{ form_start(search) }}
				<span class="icon icon-search"></span>
				{{form_widget(search.search)}}
			{{ form_end(search)}}
			</div>
		</form>
	</div>
	<div class="sidebar-box ftco-animate">
		<div class="categories">

			<h3>Categories</h3>
			{% for category in categories %}
				<li>
					<a href="{{ path('categories', {'Slug': category.Slug }) }}">{{ category.title }}
						<span class="ion-ios-arrow-forward"></span>
					</a>
				</li>
			{% endfor %}

		</div>
	</div>

	<div class="sidebar-box ftco-animate">
		<h3>Derniers articles</h3>
		{% for blogPost  in lastThreeBlogPosts %}
			<div class="block-21 mb-4 d-flex">
				<a class="blog-img mr-4" style="background-image: url({{ vich_uploader_asset(blogPost) }});"></a>
				<div class="text">
					<h3 class="heading">
						<a href="{{ path('blog_posts_show', {'Slug': blogPost.slug }) }}">{{ blogPost.title }}</a>
					</h3>
					<div class="meta">
						<div>
							<a href="{{ path('blog_posts_show', {'Slug': blogPost.slug }) }}">
								<span class="icon-calendar"></span>
								{{ blogPost.updateAt|date("d/m/Y") }}</a>
						</div>
						<div>
							<a href="{{ path('blog_posts_show', {'Slug': blogPost.slug }) }}">
								<span class="icon-person"></span>
								{{ blogPost.Author.firstname}} {{ blogPost.Author.lastname}}</a>
						</div>
						<div>
							<a href="{{ path('blog_posts_show', {'Slug': blogPost.slug }) }}">
								<span class="icon-chat"></span>
								{{ blogPost.Comments|length }}</a>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}

		

	</div>

	<div class="sidebar-box ftco-animate">
		<h3>Tag Cloud</h3>
		<div class="tagcloud">
			{% for tag in tags %}
				<a href="{{ path('tags', {'Slug': tag.Slug }) }}" class="tag-cloud-link">{{ tag.title }}</a>
			{% endfor %}

		</div>
	</div>
</div>

templates/blog_posts_show/tag.html.twig
<div class="tag-widget post-tag-container mb-5 mt-5">
	<div class="tagcloud">
		{% for tag in singlePost.tags %}
			<a href="{{ path('tags', {'Slug': tag.Slug }) }}" class="tag-cloud-link">{{ tag.title }}</a>
		{% endfor %}
	</div>
</div>